backend/accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('auth/login/', views.login_view, name='login'),
    path('auth/register/', views.registration_view, name='register'),
    path('auth/logout/', views.logout_view, name='logout'),

    path('dashboard/account/', views.user_view, name='user_edit'),
    path('dashboard/account/change-password/', views.password_change_view, name='user_password_change'),
    path('dashboard/contacts/', views.contact_list_view, name='contact_list'),
    path('dashboard/contacts/create/', views.contact_create_view, name='contact_create'),
    path('dashboard/contact/<int:contact_id>/delete/', views.contact_delete_view, name='contact_delete'),
    path('dashboard/subscriptions/', views.subscription_view, name='subscription_list'),
    path('dashboard/subscriptions/cancel/', views.cancel_subscription_view, name='cancel_subscription'),
]

backend/api/urls.py
from django.urls import path
from api.views.cart import CartItemApiView
from api.views.stream import ActiveStreamsView, StreamSessionTimeAnalyticsView, BandwidthUsageAnalyticsView
from api.views.account import subscriptionView

app_name = 'api'

urlpatterns = [
    path('cart/<int:item_id>/', CartItemApiView.as_view(), name='cart_item'),
    path('streams/active_sessions/', ActiveStreamsView.as_view(), name='active_sessions'),
    path('streams/sessions_analytics/', StreamSessionTimeAnalyticsView.as_view(), name='sessions_analytics'),
    path('streams/bandwidth_usage/', BandwidthUsageAnalyticsView.as_view(), name='bandwidth_usage'),
    path('account/subscription/', subscriptionView.as_view(), name='subscription'),
]

backend/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('shop.urls', namespace='shop')),
    path('', include('websocket.urls', namespace='websocket')),
    path('api/', include('api.urls', namespace='api')),
    path('api-auth/', include('rest_framework.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/shop/urls.py
from django.urls import path

from shop import views

app_name = 'shop'

urlpatterns = [
    path('dashboard/orders/', views.order_history_view, name='order_history'),
    path('dashboard/order/<int:order_id>/confirmation/', views.order_confirm_view, name='order_confirm'),
    path('dashboard/order/<int:order_id>/cancel/', views.cancel_order_view, name='cancel_order'),
    path('dashboard/order/<int:order_id>/', views.order_detail_view, name='order_details'),
    path('cart/add/<int:product_id>/', views.add_to_cart_view, name='add_to_cart'),
    path('cart/', views.cart_detail_view, name='cart_detail'),
    path('cart/update/', views.update_cart_item_view, name='update_cart'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('stripe/create-session/<int:order_id>/', views.create_stripe_session_view, name='stripe_create_session'),
    path('stripe/create-session/subscribtion/<int:plan_id>/', views.create_subscription_session_view, name='stripe_create_subscription_session'),
    path('stripe/webhook/', views.stripe_webhook_view, name='stripe_webhook'),
]

backend/accounts/models.py
import stripe

from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField

from core.models import BaseModel

stripe.api_key = settings.STRIPE_SECRET_KEY


# Create your models here.

class User(AbstractUser):
    email = models.EmailField(_("email address"), blank=True, unique=True)
    phone_number = PhoneNumberField(blank=True, null=True, verbose_name=_("Phone Number"))
    wallet = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        blank=True,
        null=True,
        default=0,
        verbose_name=_("Wallet"),
        validators=[MinValueValidator(0)]
    )
    last_ip = models.GenericIPAddressField(verbose_name=_("Last IP Address"), null=True, blank=True)
    stripe_customer_id = models.CharField(verbose_name=_("Stripe Customer ID"), max_length=255, blank=True, null=True)

    def __str__(self):
        return self.username

    @property
    def get_full_name(self):
        if not self.first_name and not self.last_name:
            return self.username
        return f"{self.first_name} {self.last_name}"

    @property
    def get_initials_name(self):
        if not self.first_name or not self.last_name:
            return self.username[0:2]
        return f"{self.first_name[0]}{self.last_name[0]}"

    @property
    def get_wallet_display(self):
        return f"${self.wallet}"

    def has_subscription(self):
        """
        Check if the subscription is active.
        """
        if hasattr(self, "subscription"):
            return self.subscription.status in ['active', 'trialing']
        return False

    def update_subscription_status(self):
        """
        Check the user's subscription status in Stripe and update the database.
        """
        if not self.stripe_customer_id:
            return False
        if not hasattr(self, "subscription"):
            return False

        try:
            subscription = self.subscription
            stripe_subscription = stripe.Subscription.retrieve(subscription.stripe_subscription_id)
            print(stripe_subscription)
            self.subscription.status = stripe_subscription.status
            self.subscription.save(update_fields=["status"])
            return True

        except stripe.error.StripeError as e:
            print(f"Stripe API Error: {e}")
        return False  # Error handling


class Subscription(BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='subscription')
    stripe_subscription_id = models.CharField(max_length=255, unique=True)
    plan = models.ForeignKey('main.Plans', on_delete=models.SET_NULL, null=True)
    status = models.CharField(max_length=50, default='active')

    def __str__(self):
        return f"{self.user.get_full_name} - {self.plan.name}"

    def cancel(self):
        if not self.stripe_subscription_id:
            raise ValueError("No subscription to cancel.")

        try:
            stripe.Subscription.cancel(
                self.stripe_subscription_id,
            )
            self.status = 'canceled'
            self.save(update_fields=['status'])

            return True
        except stripe.error.StripeError as e:
            raise ValueError(f"Failed to cancel subscription: {str(e)}")


class Contacts(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_("User"), related_name="contacts")
    name = models.CharField(verbose_name=_("Name"), max_length=100, help_text=_("Name of contact"))
    phone_number = PhoneNumberField(
        verbose_name=_("Phone Number"),
        help_text=_('Enter a valid phone number.')
    )

    class Meta:
        verbose_name = _("Contact")
        verbose_name_plural = _("Contacts")
        ordering = ("-created_at", "name")

    def __str__(self):
        return self.name + " " + self.phone_number

backend/accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import authenticate
from django.utils.translation import gettext_lazy as _

from .models import User, Contacts


class CustomChangePasswordForm(PasswordChangeForm):
    pass


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        exclude = ("username", "email", "is_staff", "is_active", "is_superuser", "groups", "user_permissions","date_joined","wallet")


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contacts
        exclude = ('user', 'is_active')


class LoginForm(AuthenticationForm):
    email = forms.EmailField(required=True, label=_("Email"), widget=forms.EmailInput(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].required = False

    def clean(self):
        username = self.cleaned_data.get("username")
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if (username is not None or email is not None) and password:
            if username:
                self.user_cache = authenticate(
                    self.request, username=username, password=password
                )
            else:
                self.user_cache = authenticate(
                    self.request, email=email, password=password
                )
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        help_text=_("Required. Enter a valid email address."),
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': "example@example.com"})
    )

    class Meta:
        model = User
        fields = (
            "first_name", "last_name", "email", "password1", "password2"
        )
        widgets = {
            'first_name': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': _("Enter your first name here")}
            ),
            'last_name': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': _("Enter your last name here")}
            ),
        }

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(_("A user with that email already exists."))
        return email

    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = user.email
        if commit:
            user.save()
        return user

backend/accounts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest, HttpResponse
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

from .forms import RegistrationForm, LoginForm, ContactForm, CustomUserChangeForm, CustomChangePasswordForm
from .decorators import unauthenticated_user
from .models import Contacts

from main.models import Plans
from core.utils import fancy_message


def user_view(request: HttpRequest, *args, **kwargs) -> HttpResponse:
    form = CustomUserChangeForm(instance=request.user)
    password_form = CustomChangePasswordForm(user=request.user)

    if request.method == "POST":
        form = CustomUserChangeForm(data=request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            fancy_message(request, "You have successfully changed your account.", "success")
            return redirect(".")
        else:
            fancy_message(request, "Please make sure to fill fields correctly.", "error")
            print(form.errors)
    context = {
        "active_tab": "account",
        "title": "Account | Eye Security",
        "form": form,
        "password_form": password_form,
    }
    return render(request, 'accounts/account.html', context)


@login_required
@require_POST
def password_change_view(request: HttpRequest, *args, **kwargs) -> HttpResponse:
    form = CustomChangePasswordForm(user=request.user, data=request.POST)
    if form.is_valid():
        form.save()
        fancy_message(request, "You have successfully changed your password.", "success")
        return redirect("accounts:user_edit")
    else:
        fancy_message(request, form.errors, "error")
        return redirect("accounts:user_edit")


@unauthenticated_user
def login_view(request: HttpRequest, *args, **kwargs) -> HttpResponse:
    form = LoginForm()
    next_url = request.GET.get('next', None)
    if request.method == "POST":
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user, backend='accounts.backends.EmailBackend')
            fancy_message(request, "Welcome {}".format(user.username), "success")
            if next_url:
                return redirect(next_url)
            return redirect("main:dashboard")
        else:
            fancy_message(request, "Invalid username or password.", "error")
    context = {
        "title": "Sign In to defensive eye account",
        "form": form,
    }
    return render(request, "accounts/login.html", context)


@unauthenticated_user
def registration_view(request: HttpRequest, *args, **kwargs) -> HttpResponse:
    form = RegistrationForm()
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user, backend='accounts.backends.EmailBackend')
            fancy_message(request, "Welcome {}".format(user.username), "success")
            return redirect("main:dashboard")
        else:
            fancy_message(request, form.errors, "error")
    context = {
        "title": "Sign up in defensive eye",
        "form": form,
    }
    return render(request, "accounts/register.html", context)


@login_required
def logout_view(request: HttpRequest, *args, **kwargs) -> HttpResponse:
    logout(request)
    fancy_message(request, "You have been logged out successfully.", "success")

    return redirect("main:home")


@login_required
def contact_list_view(request: HttpRequest, *args, **kwargs) -> HttpResponse:
    contacts = Contacts.objects.filter(user=request.user, is_active=True)

    paginator = Paginator(contacts, 10)
    page = request.GET.get('page', 1)

    paged_contacts = paginator.get_page(page)

    context = {
        "active_tab": "contacts",
        "title": "Contact list",
        "contacts": paged_contacts,
    }

    if request.htmx:
        return render(request, "accounts/components/contact_list_result.html", context)

    return render(request, "accounts/contact_list.html", context)


@login_required
def contact_create_view(request: HttpRequest, *args, **kwargs) -> HttpResponse:
    form = ContactForm()
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.user = request.user
            contact.save()
            fancy_message(request, "New contact added successfully.", "success")
            return redirect("accounts:contact_list")
        else:
            fancy_message(request, "Resolve the errors and try again.", "error")
    context = {
        "active_tab": "contacts",
        "title": "Contact list",
        "form": form,
    }
    return render(request, "accounts/contact_create.html", context)


@login_required
def contact_delete_view(request: HttpRequest, contact_id, *args, **kwargs) -> HttpResponse:
    contact = get_object_or_404(Contacts, id=contact_id, user=request.user)
    contact.delete()
    fancy_message(request, "Contact deleted successfully.", "success")
    return redirect("accounts:contact_list")


@login_required
def subscription_view(request: HttpRequest, *args, **kwargs) -> HttpResponse:
    plans = Plans.objects.filter(is_active=True).order_by("created_at")

    context = {
        "active_tab": "subscriptions",
        "title": "Subscription plans",
        "plans": plans,
    }

    return render(request, 'accounts/subscription_list.html', context)


@login_required
def cancel_subscription_view(request):
    user = request.user

    if not hasattr(user, 'subscription'):
        fancy_message(request, "You have no subscription yet.", "error")
        return redirect("accounts:subscription_list")

    try:
        user.subscription.cancel()
        fancy_message(request, "Subscription canceled successfully.", "success")
        return redirect("accounts:subscription_list")
    except ValueError as e:
        fancy_message(request, "Something went wrong.please try later.", "error")
        print("cancel subscription error: {}".format(e))
        return redirect("accounts:subscription_list")

backend/api/views/account.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.request import Request

from api.serializers import SubscriptionSerializer, PlansSerializer


class subscriptionView(APIView):

    def get(self, request: Request, format=None):
        user = request.user

        if user.has_subscription():
            subscription = user.subscription
            plan = subscription.plan
            plan_serializer = PlansSerializer(plan)
            subscription_serializer = SubscriptionSerializer(subscription)

            data = {
                "plan": plan_serializer.data,
                "subscription": subscription_serializer.data
            }

            return Response(data,status=status.HTTP_200_OK)
        else:
            return Response(status=status.HTTP_402_PAYMENT_REQUIRED)

backend/templates/accounts/components/contact_list_result.html
{% load i18n %}
<section id="contact-section" class="w-full card max-w-none">
    <div class="flex justify-between">
        <h1 class="text-2xl font-semibold text-gray-600">{% translate 'My Contacts' %}</h1>
        <a href="{% url 'accounts:contact_create' %}" class="btn btn-primary">
            <i class="fa-solid fa-plus"></i>
            {% translate 'Add Contact' %}
        </a>
    </div>
    <div class="mt-6 flow-root sm:mt-8 table-container">
        <table class="table">
            <thead class="table-head">
            <tr>
                <th scope="col"
                    class="table-cell">
                    {% translate "#" %}
                </th>
                <th scope="col"
                    class="table-cell">
                    {% translate "Name" %}
                </th>
                <th scope="col"
                    class="table-cell">
                    {% translate "Phone" %}
                </th>
                <th scope="col"
                    class="table-cell">
                    {% translate "Actions" %}
                </th>
            </tr>
            </thead>
            <tbody id="table-body">
            {% for item in contacts %}
                <tr class="table-tr">
                    <th class="table-th">
                        #{{ contacts.id }}
                    </th>
                    <td class="table-cell">
                        {{ item.name }}
                    </td>
                    <td class="table-cell">
                        {{ item.phone_number }}
                    </td>
                    <td class="table-cell">
                        <a href="{% url 'accounts:contact_delete' item.id %}"
                           class="ml-4 text-danger-600 hover:underline ">
                            {% translate "Delete" %}
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="mt-6">
        <div class="flex justify-between items-center">
            {% if contacts.has_previous %}
                <button hx-get="?page={{ contacts.previous_page_number }}" hx-target="#contact-section"
                        hx-swap="outerHTML"
                        hx-push-url="true"
                        class="flex items-center justify-center px-3 h-8 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
                    <i class="fa-solid fa-arrow-left me-2"></i>
                    {% translate "Previous" %}
                </button>
            {% endif %}
            <span class="text-gray-500 text-sm">{% translate "Page" %} {{ contacts.number }} {% translate "of" %} {{ contacts.paginator.num_pages }}</span>
            {% if contacts.has_next %}
                <button hx-get="?page={{ contacts.next_page_number }}" hx-target="#contact-section" hx-swap="outerHTML"
                        hx-push-url="true"
                        class="flex items-center justify-center px-3 h-8 ms-3 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
                    {% translate "Next" %}
                    <i class="fa-solid fa-arrow-right ms-2"></i>
                </button>
            {% endif %}
        </div>
    </div>
</section>

backend/templates/accounts/components/subscription_list.html
{% load i18n %}
<section class=" dark:bg-gray-900">
    <div class="py-8 px-4 mx-auto max-w-screen-xl lg:py-16 lg:px-6">
        <div class="mx-auto max-w-screen-md text-center mb-8 lg:mb-12">
            <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">
                Secure Solutions for Every Need
            </h2>
            <p class="mb-5 font-light text-gray-500 sm:text-xl dark:text-gray-400">At eye security, we
                specialize in providing advanced security camera systems for personal, home, and business use. With
                features like online video streaming and more, we help you stay connected and protected, anytime,
                anywhere.</p>

        </div>
        <div class=" grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3 gap-3 sm:gap-6 xl:gap-10 lg:space-y-0">
            {% for plan in plans %}
                <!-- Pricing Card -->
                <div class="relative flex flex-col p-6 mx-auto max-w-lg text-center overflow-hidden text-gray-900 bg-white rounded-lg border border-gray-100 shadow dark:border-gray-600 xl:p-8 dark:bg-gray-800 dark:text-white">
                    {% if request.user.has_subscription and request.user.subscription.plan.id == plan.id %}
                        <span class="absolute top-5 -left-10 bg-warning-700 text-white p-2 -rotate-45 w-40">Subscribed</span>
                    {% endif %}
                    <h3 class="mb-4 text-2xl font-semibold">{{ plan.name }}</h3>
                    <p class="font-light text-gray-500 sm:text-lg dark:text-gray-400">{{ plan.description }}</p>
                    <div class="flex justify-center items-baseline my-8">
                        <span class="mr-2 text-5xl font-extrabold">${{ plan.price }}</span>
                        <span class="text-gray-500 dark:text-gray-400">/month</span>
                    </div>
                    <!-- List -->
                    <ul role="list" class="mb-8 space-y-4 text-left flex-grow">
                        {% for item in plan.get_items %}
                            <li class="flex items-center space-x-3">
                                <!-- Icon -->
                                <svg class="flex-shrink-0 w-5 h-5 text-green-500 dark:text-green-400"
                                     fill="currentColor"
                                     viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd"
                                          d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                                          clip-rule="evenodd"></path>
                                </svg>
                                <span>{{ item.name }}</span>
                            </li>
                        {% endfor %}
                    </ul>
                    {% if request.user.has_subscription %}
                        {% if request.user.subscription.plan.id == plan.id %}
                            <button data-modal-target="cancel-subscription-modal"
                                    data-modal-toggle="cancel-subscription-modal"
                                    class="btn btn-danger"
                                    type="button">
                                {% translate 'Cancel subscription' %}
                            </button>
                        {% else %}
                        {% endif %}
                    {% else %}
                        <a href="{% url 'shop:stripe_create_subscription_session' plan.id %}"
                           class="btn btn-primary">{% translate 'Subscribe' %}</a>
                    {% endif %}

                </div>
            {% endfor %}


        </div>
    </div>

    <!-- Cancel subscription modal -->
    <div id="cancel-subscription-modal" tabindex="-1" aria-hidden="true"
         class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
        <div class="relative p-4 w-full max-w-2xl max-h-full">
            <!-- Modal content -->
            <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                <!-- Modal header -->
                <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
                    <h3 class="text-xl font-semibold text-gray-900 dark:text-white">
                        Cancel Subscription
                    </h3>
                    <button type="button"
                            class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white"
                            data-modal-hide="cancel-subscription-modal">
                        <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                             viewBox="0 0 14 14">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                  d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                        </svg>
                        <span class="sr-only">Close modal</span>
                    </button>
                </div>
                <!-- Modal body -->
                <div class="p-4 md:p-5 space-y-4">
                    <p class="text-base leading-relaxed text-gray-500 dark:text-gray-400">
                        Are you sure you want to cancel your subscription? You will lose access to all premium features
                        immediately upon cancellation.
                    </p>
                    <p class="text-base leading-relaxed text-gray-500 dark:text-gray-400">
                        This action cannot be undone. If you wish to continue using the premium features, please keep
                        your subscription active.
                    </p>
                </div>
                <!-- Modal footer -->
                <div class="flex items-center p-4 md:p-5 border-t border-gray-200 rounded-b dark:border-gray-600">
                    <a href="{% url 'accounts:cancel_subscription' %}" id="confirm-cancel-subscription" type="button"
                       class="text-white bg-red-600 hover:bg-red-700 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-red-500 dark:hover:bg-red-600 dark:focus:ring-red-900">
                        Confirm Cancellation
                    </a>
                    <button data-modal-hide="cancel-subscription-modal" type="button"
                            class="py-2.5 px-5 ms-3 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-100 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">
                        Keep Subscription
                    </button>
                </div>
            </div>
        </div>
    </div>
</section>