backend/accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('auth/login/', views.login_view, name='login'),
    path('auth/register/', views.registration_view, name='register'),
    path('auth/logout/', views.logout_view, name='logout'),

    path('dashboard/account/', views.user_view, name='user_edit'),
    path('dashboard/account/change-password/', views.password_change_view, name='user_password_change'),
    path('dashboard/contacts/', views.contact_list_view, name='contact_list'),
    path('dashboard/contacts/create/', views.contact_create_view, name='contact_create'),
    path('dashboard/contact/<int:contact_id>/delete/', views.contact_delete_view, name='contact_delete'),
    path('dashboard/subscriptions/', views.subscription_view, name='subscription_list'),
    path('dashboard/subscriptions/cancel/', views.cancel_subscription_view, name='cancel_subscription'),
]

backend/api/urls.py
from django.urls import path
from api.views.cart import CartItemApiView
from api.views.stream import ActiveStreamsView, StreamSessionTimeAnalyticsView, BandwidthUsageAnalyticsView
from api.views.account import subscriptionView

app_name = 'api'

urlpatterns = [
    path('cart/<int:item_id>/', CartItemApiView.as_view(), name='cart_item'),
    path('streams/active_sessions/', ActiveStreamsView.as_view(), name='active_sessions'),
    path('streams/sessions_analytics/', StreamSessionTimeAnalyticsView.as_view(), name='sessions_analytics'),
    path('streams/bandwidth_usage/', BandwidthUsageAnalyticsView.as_view(), name='bandwidth_usage'),
    path('account/subscription/', subscriptionView.as_view(), name='subscription'),
]

backend/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('shop.urls', namespace='shop')),
    path('', include('websocket.urls', namespace='websocket')),
    path('api/', include('api.urls', namespace='api')),
    path('api-auth/', include('rest_framework.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/accounts/models.py
import stripe

from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField

from core.models import BaseModel

stripe.api_key = settings.STRIPE_SECRET_KEY


# Create your models here.

class User(AbstractUser):
    email = models.EmailField(_("email address"), blank=True, unique=True)
    phone_number = PhoneNumberField(blank=True, null=True, verbose_name=_("Phone Number"))
    wallet = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        blank=True,
        null=True,
        default=0,
        verbose_name=_("Wallet"),
        validators=[MinValueValidator(0)]
    )
    last_ip = models.GenericIPAddressField(verbose_name=_("Last IP Address"), null=True, blank=True)
    stripe_customer_id = models.CharField(verbose_name=_("Stripe Customer ID"), max_length=255, blank=True, null=True)

    def __str__(self):
        return self.username

    @property
    def get_full_name(self):
        if not self.first_name and not self.last_name:
            return self.username
        return f"{self.first_name} {self.last_name}"

    @property
    def get_initials_name(self):
        if not self.first_name or not self.last_name:
            return self.username[0:2]
        return f"{self.first_name[0]}{self.last_name[0]}"

    @property
    def get_wallet_display(self):
        return f"${self.wallet}"

    def has_subscription(self):
        """
        Check if the subscription is active.
        """
        if hasattr(self, "subscription"):
            return self.subscription.status in ['active', 'trialing']
        return False

    def update_subscription_status(self):
        """
        Check the user's subscription status in Stripe and update the database.
        """
        if not self.stripe_customer_id:
            return False
        if not hasattr(self, "subscription"):
            return False

        try:
            subscription = self.subscription
            stripe_subscription = stripe.Subscription.retrieve(subscription.stripe_subscription_id)
            print(stripe_subscription)
            self.subscription.status = stripe_subscription.status
            self.subscription.save(update_fields=["status"])
            return True

        except stripe.error.StripeError as e:
            print(f"Stripe API Error: {e}")
        return False  # Error handling


class Subscription(BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='subscription')
    stripe_subscription_id = models.CharField(max_length=255, unique=True)
    plan = models.ForeignKey('main.Plans', on_delete=models.SET_NULL, null=True)
    status = models.CharField(max_length=50, default='active')

    def __str__(self):
        return f"{self.user.get_full_name} - {self.plan.name}"

    def cancel(self):
        if not self.stripe_subscription_id:
            raise ValueError("No subscription to cancel.")

        try:
            stripe.Subscription.cancel(
                self.stripe_subscription_id,
            )
            self.status = 'canceled'
            self.save(update_fields=['status'])

            return True
        except stripe.error.StripeError as e:
            raise ValueError(f"Failed to cancel subscription: {str(e)}")


class Contacts(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_("User"), related_name="contacts")
    name = models.CharField(verbose_name=_("Name"), max_length=100, help_text=_("Name of contact"))
    phone_number = PhoneNumberField(
        verbose_name=_("Phone Number"),
        help_text=_('Enter a valid phone number.')
    )

    class Meta:
        verbose_name = _("Contact")
        verbose_name_plural = _("Contacts")
        ordering = ("-created_at", "name")

    def __str__(self):
        return self.name + " " + self.phone_number

backend/accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import authenticate
from django.utils.translation import gettext_lazy as _

from .models import User, Contacts


class CustomChangePasswordForm(PasswordChangeForm):
    pass


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        exclude = ("username", "email", "is_staff", "is_active", "is_superuser", "groups", "user_permissions","date_joined","wallet")


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contacts
        exclude = ('user', 'is_active')


class LoginForm(AuthenticationForm):
    email = forms.EmailField(required=True, label=_("Email"), widget=forms.EmailInput(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].required = False

    def clean(self):
        username = self.cleaned_data.get("username")
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if (username is not None or email is not None) and password:
            if username:
                self.user_cache = authenticate(
                    self.request, username=username, password=password
                )
            else:
                self.user_cache = authenticate(
                    self.request, email=email, password=password
                )
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        help_text=_("Required. Enter a valid email address."),
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': "example@example.com"})
    )

    class Meta:
        model = User
        fields = (
            "first_name", "last_name", "email", "password1", "password2"
        )
        widgets = {
            'first_name': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': _("Enter your first name here")}
            ),
            'last_name': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': _("Enter your last name here")}
            ),
        }

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(_("A user with that email already exists."))
        return email

    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = user.email
        if commit:
            user.save()
        return user

backend/accounts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest, HttpResponse
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

from .forms import RegistrationForm, LoginForm, ContactForm, CustomUserChangeForm, CustomChangePasswordForm
from .decorators import unauthenticated_user
from .models import Contacts

from main.models import Plans
from core.utils import fancy_message


def user_view(request: HttpRequest, *args, **kwargs) -> HttpResponse:
    form = CustomUserChangeForm(instance=request.user)
    password_form = CustomChangePasswordForm(user=request.user)

    if request.method == "POST":
        form = CustomUserChangeForm(data=request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            fancy_message(request, "You have successfully changed your account.", "success")
            return redirect(".")
        else:
            fancy_message(request, "Please make sure to fill fields correctly.", "error")
            print(form.errors)
    context = {
        "active_tab": "account",
        "title": "Account | Eye Security",
        "form": form,
        "password_form": password_form,
    }
    return render(request, 'accounts/account.html', context)


@login_required
@require_POST
def password_change_view(request: HttpRequest, *args, **kwargs) -> HttpResponse:
    form = CustomChangePasswordForm(user=request.user, data=request.POST)
    if form.is_valid():
        form.save()
        fancy_message(request, "You have successfully changed your password.", "success")
        return redirect("accounts:user_edit")
    else:
        fancy_message(request, form.errors, "error")
        return redirect("accounts:user_edit")


@unauthenticated_user
def login_view(request: HttpRequest, *args, **kwargs) -> HttpResponse:
    form = LoginForm()
    next_url = request.GET.get('next', None)
    if request.method == "POST":
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user, backend='accounts.backends.EmailBackend')
            fancy_message(request, "Welcome {}".format(user.username), "success")
            if next_url:
                return redirect(next_url)
            return redirect("main:dashboard")
        else:
            fancy_message(request, "Invalid username or password.", "error")
    context = {
        "title": "Sign In to defensive eye account",
        "form": form,
    }
    return render(request, "accounts/login.html", context)


@unauthenticated_user
def registration_view(request: HttpRequest, *args, **kwargs) -> HttpResponse:
    form = RegistrationForm()
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user, backend='accounts.backends.EmailBackend')
            fancy_message(request, "Welcome {}".format(user.username), "success")
            return redirect("main:dashboard")
        else:
            fancy_message(request, form.errors, "error")
    context = {
        "title": "Sign up in defensive eye",
        "form": form,
    }
    return render(request, "accounts/register.html", context)


@login_required
def logout_view(request: HttpRequest, *args, **kwargs) -> HttpResponse:
    logout(request)
    fancy_message(request, "You have been logged out successfully.", "success")

    return redirect("main:home")


@login_required
def contact_list_view(request: HttpRequest, *args, **kwargs) -> HttpResponse:
    contacts = Contacts.objects.filter(user=request.user, is_active=True)

    paginator = Paginator(contacts, 10)
    page = request.GET.get('page', 1)

    paged_contacts = paginator.get_page(page)

    context = {
        "active_tab": "contacts",
        "title": "Contact list",
        "contacts": paged_contacts,
    }

    if request.htmx:
        return render(request, "accounts/components/contact_list_result.html", context)

    return render(request, "accounts/contact_list.html", context)


@login_required
def contact_create_view(request: HttpRequest, *args, **kwargs) -> HttpResponse:
    form = ContactForm()
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.user = request.user
            contact.save()
            fancy_message(request, "New contact added successfully.", "success")
            return redirect("accounts:contact_list")
        else:
            fancy_message(request, "Resolve the errors and try again.", "error")
    context = {
        "active_tab": "contacts",
        "title": "Contact list",
        "form": form,
    }
    return render(request, "accounts/contact_create.html", context)


@login_required
def contact_delete_view(request: HttpRequest, contact_id, *args, **kwargs) -> HttpResponse:
    contact = get_object_or_404(Contacts, id=contact_id, user=request.user)
    contact.delete()
    fancy_message(request, "Contact deleted successfully.", "success")
    return redirect("accounts:contact_list")


@login_required
def subscription_view(request: HttpRequest, *args, **kwargs) -> HttpResponse:
    plans = Plans.objects.filter(is_active=True).order_by("created_at")

    context = {
        "active_tab": "subscriptions",
        "title": "Subscription plans",
        "plans": plans,
    }

    return render(request, 'accounts/subscription_list.html', context)


@login_required
def cancel_subscription_view(request):
    user = request.user

    if not hasattr(user, 'subscription'):
        fancy_message(request, "You have no subscription yet.", "error")
        return redirect("accounts:subscription_list")

    try:
        user.subscription.cancel()
        fancy_message(request, "Subscription canceled successfully.", "success")
        return redirect("accounts:subscription_list")
    except ValueError as e:
        fancy_message(request, "Something went wrong.please try later.", "error")
        print("cancel subscription error: {}".format(e))
        return redirect("accounts:subscription_list")

backend/api/views/account.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.request import Request

from api.serializers import SubscriptionSerializer, PlansSerializer


class subscriptionView(APIView):

    def get(self, request: Request, format=None):
        user = request.user

        if user.has_subscription():
            subscription = user.subscription
            plan = subscription.plan
            plan_serializer = PlansSerializer(plan)
            subscription_serializer = SubscriptionSerializer(subscription)

            data = {
                "plan": plan_serializer.data,
                "subscription": subscription_serializer.data
            }

            return Response(data,status=status.HTTP_200_OK)
        else:
            return Response(status=status.HTTP_402_PAYMENT_REQUIRED)

backend/templates/accounts/account.html
{% extends 'web/base_dashboard.html' %}
{% load widget_tweaks %}
{% load i18n %}
{% block dashboard_content %}
    <section class="w-full card max-w-none">
        <h2 class="text-2xl font-bold text-gray-900 mb-4">{% translate 'Information' %}</h2>
        <form action="{% url 'accounts:user_edit' %}" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            <div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
                <div class="col-span-1 ">
                    <label class="input-label"
                           for="{{ form.email.id_for_label }}">Email</label>
                    <input type="email" id="id_email" value="{{ request.user.email }}" class="form-control" disabled>
                    <small class="text-gray-500 text-xs">{{ form.email.help_text }}</small>
                    <small class="text-danger-500 text-xs">{{ form.email.errors }}</small>
                </div>
                <div class="col-span-1 ">
                    <label class="input-label"
                           for="{{ form.first_name.id_for_label }}">{{ form.first_name.label }}</label>
                    {{ form.first_name|add_class:"form-control" }}
                    <small class="text-gray-500 text-xs">{{ form.first_name.help_text }}</small>
                    <small class="text-danger-500 text-xs">{{ form.first_name.errors }}</small>
                </div>
                <div class="col-span-1 ">
                    <label class="input-label"
                           for="{{ form.last_name.id_for_label }}">{{ form.last_name.label }}</label>
                    {{ form.last_name|add_class:"form-control" }}
                    <small class="text-gray-500 text-xs">{{ form.last_name.help_text }}</small>
                    <small class="text-danger-500 text-xs">{{ form.last_name.errors }}</small>
                </div>
                <div class="col-span-1 ">
                    <label class="input-label"
                           for="{{ form.phone_number.id_for_label }}">{{ form.phone_number.label }}</label>
                    {{ form.phone_number|add_class:"form-control" }}
                    <small class="text-gray-500 text-xs">{{ form.phone_number.help_text }}</small>
                    <small class="text-danger-500 text-xs">{{ form.phone_number.errors }}</small>
                </div>
                <div class="col-span-1 ">
                    <button class="btn btn-primary" type="submit">{% translate 'Save' %}</button>
                </div>
            </div>
        </form>
    </section>
    <section class="w-full card max-w-none mt-6">
        <h2 class="text-2xl font-bold text-gray-900 mb-4">{% translate 'Change Password' %}</h2>
        <form action="{% url 'accounts:user_password_change' %}" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            <div class="grid grid-cols-1 lg:grid-cols-1 gap-4">
                <div class="col-span-1 max-w-xl">
                    <label class="input-label"
                           for="{{ password_form.old_password.id_for_label }}">{{ password_form.old_password.label }}</label>
                    {{ password_form.old_password|add_class:"form-control" }}
                    <small class="text-gray-500 text-xs">{{ password_form.old_password.help_text }}</small>
                    <small class="text-danger-500 text-xs">{{ password_form.old_password.errors }}</small>
                </div>
                <div class="col-span-1 max-w-xl">
                    <label class="input-label"
                           for="{{ password_form.new_password1.id_for_label }}">{{ password_form.new_password1.label }}</label>
                    {{ password_form.new_password1|add_class:"form-control" }}
                    <small class="text-gray-500 text-xs">{{ password_form.new_password1.help_text }}</small>
                    <small class="text-danger-500 text-xs">{{ password_form.new_password1.errors }}</small>
                </div>
                <div class="col-span-1 max-w-xl">
                    <label class="input-label"
                           for="{{ password_form.new_password2.id_for_label }}">{{ password_form.new_password2.label }}</label>
                    {{ password_form.new_password2|add_class:"form-control" }}
                    <small class="text-gray-500 text-xs">{{ password_form.new_password2.help_text }}</small>
                    <small class="text-danger-500 text-xs">{{ password_form.new_password2.errors }}</small>
                </div>
                <div class="col-span-1 ">
                    <button class="btn btn-primary" type="submit">{% translate 'Change Password' %}</button>
                </div>
            </div>
        </form>
    </section>
{% endblock %}

backend/templates/accounts/contact_create.html
{% extends 'web/base_dashboard.html' %}
{% load widget_tweaks %}
{% load i18n %}
{% block dashboard_content %}
    <section class="w-full card max-w-none">
        <form action="." enctype="multipart/form-data" method="post">
            {% csrf_token %}
            <div class="grid grid-cols-1 lg:grid-cols-1 gap-4">
                <div class="col-span-1 max-w-lg">
                    <label class="input-label"
                           for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
                    {{ form.name|add_class:"form-control" }}
                    <small class="text-gray-500 text-xs">{{ form.name.help_text }}</small>
                    <small class="text-danger-500 text-xs">{{ form.name.errors }}</small>
                </div>
                <div class="col-span-1 max-w-lg">
                    <label class="input-label"
                           for="{{ form.phone_number.id_for_label }}">{{ form.phone_number.label }}</label>
                    {{ form.phone_number|add_class:"form-control" }}
                    <small class="text-gray-500 text-xs">{{ form.phone_number.help_text }}</small>
                    <small class="text-danger-500 text-xs">{{ form.phone_number.errors }}</small>
                </div>
                <div class="col-span-1 max-w-lg">
                    <button class="btn btn-primary" type="submit">{% translate 'Save' %}</button>
                </div>
            </div>
        </form>
    </section>
{% endblock %}

backend/templates/accounts/contact_list.html
{% extends 'web/base_dashboard.html' %}
{% block dashboard_content %}
    {% include 'accounts/components/contact_list_result.html' %}
{% endblock %}

backend/templates/accounts/login.html
{% extends 'web/base.html' %}
{% load i18n %}
{% load widget_tweaks %}
{% block content %}
    <section class="container flex justify-center items-center my-24">
        <div class="bg-white shadow-lg p-6 rounded-lg w-full max-w-lg">
            <h1 class="text-2xl font-bold mb-6">{% translate 'Sign in to your account' %}</h1>
            <form action="{% url 'accounts:login' %}" enctype="multipart/form-data" method="post">
                {% csrf_token %}
                <div class="flex flex-col mb-4">
                    <label for="{{ form.email.id_for_label }}" class="input-label">{{ form.email.label }}</label>
                    {{ form.email|add_class:"form-control" }}
                    <small class="text-danger-500">{{ form.email.errors }}</small>
                </div>
                <div class="flex flex-col mb-4">
                    <label for="{{ form.password.id_for_label }}" class="input-label">{{ form.password.label }}</label>
                    {{ form.password|add_class:"form-control" }}
                    <small class="text-danger-500">{{ form.password.errors }}</small>
                </div>
                <div class="mb-4">

                    <a href="#" class="text-primary-800 hover:underline font-bold text-md">Forget Password</a>
                </div>
                <div class="mb-4">
                    <button class="btn btn-gradient-primary w-full" type="submit">{% translate 'Sign In' %}</button>
                </div>
                <div>
                    <p class="text-gray-500 font-medium">Don’t have an account yet?
                        <a href="{% url 'accounts:register' %}"
                           class="text-primary-800 text-md">{% translate 'Sign up' %}</a>
                    </p>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

backend/templates/accounts/register.html
{% extends 'web/base.html' %}
{% load i18n %}
{% load widget_tweaks %}
{% block content %}
    <section class="container flex justify-center items-center my-24">
        <div class="bg-white shadow-lg p-6 rounded-lg w-full max-w-lg">
            <h1 class="text-2xl font-bold mb-6">{% translate 'Create an account' %}</h1>
            <form action="{% url 'accounts:register' %}" enctype="multipart/form-data" method="post">
                {% csrf_token %}
                <div class="flex flex-col mb-4">
                    <label for="{{ form.email.id_for_label }}" class="input-label">{{ form.email.label }}</label>
                    {{ form.email|add_class:"form-control" }}
                    <small class="text-danger-500">{{ form.email.errors }}</small>
                </div>
                <div class="flex justify-between items-center">
                    <div class="flex flex-col mb-4">
                        <label for="{{ form.first_name.id_for_label }}"
                               class="input-label">{{ form.first_name.label }}</label>
                        {{ form.first_name|add_class:"form-control" }}
                        <small class="text-danger-500">{{ form.first_name.errors }}</small>
                    </div>
                    <div class="flex flex-col mb-4">
                        <label for="{{ form.last_name.id_for_label }}"
                               class="input-label">{{ form.last_name.label }}</label>
                        {{ form.last_name|add_class:"form-control" }}
                        <small class="text-danger-500">{{ form.last_name.errors }}</small>
                    </div>
                </div>

                <div class="flex flex-col mb-4">
                    <label for="{{ form.password1.id_for_label }}"
                           class="input-label">{{ form.password1.label }}</label>
                    {{ form.password1|add_class:"form-control"|attr:"placeholder:••••••••" }}
                    <small class="text-danger-500">{{ form.password1.errors }}</small>
                    <div class="text-xs p-2 bg-gray-100 rounded-lg my-2">
                        {{ form.password1.help_text }}
                    </div>
                </div>
                <div class="flex flex-col mb-4">
                    <label for="{{ form.password2.id_for_label }}"
                           class="input-label">{{ form.password2.label }}</label>
                    {{ form.password2|add_class:"form-control"|attr:"placeholder:••••••••" }}
                    <small class="text-danger-500">{{ form.password2.errors }}</small>
                </div>
                <div class="mb-4">
                    <button class="btn btn-gradient-primary w-full" type="submit">{% translate 'Sign Up' %}</button>
                </div>
                <div>
                    <p class="text-gray-500 font-medium">Already have an account?
                        <a href="{% url 'accounts:login' %}"
                           class="text-primary-800 text-md">{% translate 'Login here' %}</a>
                    </p>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

backend/templates/accounts/subscription_list.html
{% extends 'web/base_dashboard.html' %}
{% load i18n %}
{% block dashboard_content %}
    {% include 'accounts/components/subscription_list.html' %}
{% endblock %}