backend/accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('auth/login/', views.login_view, name='login'),
    path('auth/register/', views.registration_view, name='register'),
    path('auth/logout/', views.logout_view, name='logout'),

    path('dashboard/account/', views.user_view, name='user_edit'),
    path('dashboard/account/change-password/', views.password_change_view, name='user_password_change'),
    path('dashboard/contacts/', views.contact_list_view, name='contact_list'),
    path('dashboard/contacts/create/', views.contact_create_view, name='contact_create'),
    path('dashboard/contact/<int:contact_id>/delete/', views.contact_delete_view, name='contact_delete'),
    path('dashboard/subscriptions/', views.subscription_view, name='subscription_list'),
    path('dashboard/subscriptions/cancel/', views.cancel_subscription_view, name='cancel_subscription'),
]

backend/api/urls.py
from django.urls import path
from api.views.cart import CartItemApiView
from api.views.stream import ActiveStreamsView, StreamSessionTimeAnalyticsView, BandwidthUsageAnalyticsView
from api.views.account import subscriptionView

app_name = 'api'

urlpatterns = [
    path('cart/<int:item_id>/', CartItemApiView.as_view(), name='cart_item'),
    path('streams/active_sessions/', ActiveStreamsView.as_view(), name='active_sessions'),
    path('streams/sessions_analytics/', StreamSessionTimeAnalyticsView.as_view(), name='sessions_analytics'),
    path('streams/bandwidth_usage/', BandwidthUsageAnalyticsView.as_view(), name='bandwidth_usage'),
    path('account/subscription/', subscriptionView.as_view(), name='subscription'),
]

backend/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('shop.urls', namespace='shop')),
    path('', include('websocket.urls', namespace='websocket')),
    path('api/', include('api.urls', namespace='api')),
    path('api-auth/', include('rest_framework.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/main/urls.py
from django.urls import path
from .views import home_view, dashboard_view, product_view, camera_list_view

app_name = 'main'

urlpatterns = [
    path('', home_view, name='home'),
    path('dashboard/', dashboard_view, name='dashboard'),
    path('product/<slug:slug>/', product_view, name='product'),
    path('dashboard/cameras/', camera_list_view, name='cameras_list'),

]

backend/shop/urls.py
from django.urls import path

from shop import views

app_name = 'shop'

urlpatterns = [
    path('dashboard/orders/', views.order_history_view, name='order_history'),
    path('dashboard/order/<int:order_id>/confirmation/', views.order_confirm_view, name='order_confirm'),
    path('dashboard/order/<int:order_id>/cancel/', views.cancel_order_view, name='cancel_order'),
    path('dashboard/order/<int:order_id>/', views.order_detail_view, name='order_details'),
    path('cart/add/<int:product_id>/', views.add_to_cart_view, name='add_to_cart'),
    path('cart/', views.cart_detail_view, name='cart_detail'),
    path('cart/update/', views.update_cart_item_view, name='update_cart'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('stripe/create-session/<int:order_id>/', views.create_stripe_session_view, name='stripe_create_session'),
    path('stripe/create-session/subscribtion/<int:plan_id>/', views.create_subscription_session_view, name='stripe_create_subscription_session'),
    path('stripe/webhook/', views.stripe_webhook_view, name='stripe_webhook'),
]

backend/templates/web/components/footer.html
<footer class="bg-white rounded-lg shadow dark:bg-gray-900">
    <div class="w-full max-w-screen-xl mx-auto p-4 md:py-8">
        <div class="sm:flex sm:items-center sm:justify-between">
            <a href="/" class="flex items-center mb-4 sm:mb-0 space-x-3 rtl:space-x-reverse">
                <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Flowbite Logo"/>
                <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Defensive Eye</span>
            </a>
            <ul class="flex flex-wrap items-center mb-6 text-sm font-medium text-gray-500 sm:mb-0 dark:text-gray-400">
                <li>
                    <a href="#" class="hover:underline me-4 md:me-6">About</a>
                </li>
                <li>
                    <a href="#" class="hover:underline me-4 md:me-6">Privacy Policy</a>
                </li>
                <li>
                    <a href="#" class="hover:underline me-4 md:me-6">Licensing</a>
                </li>
                <li>
                    <a href="#" class="hover:underline">Contact</a>
                </li>
            </ul>
        </div>
        <hr class="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8"/>
        <span class="block text-sm text-gray-500 sm:text-center dark:text-gray-400">
            © <span id="footer-copy-law">2023</span>
            <a href="/" class="hover:underline">Defensive Eye™</a>
            . All Rights Reserved.
        </span>
    </div>
</footer>

backend/templates/web/components/mega_menu.html
{% load i18n %}
<div class="mega-menu" id="mega-menu">
    <div class="grid grid-cols-1 lg:grid-cols-3 space-x-4 p-4">
        {% for type,products in products_by_type.items %}
            <div class="col-span-1">
                <h3 class="text-green-900 font-bold bg-gray-100 py-1 px-2 text-lg">{{ type }}</h3>
                <ul>
                    {% for product in products %}
                        <li class="px-2 my-2">
                            <a href="{{ product.get_absolute_url }}" class="link hover:underline">
                                {{ product.name }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% endfor %}
    </div>
</div>

backend/templates/web/components/navbar.html
{% load i18n %}

{% url 'main:home' as home_url %}
{% url 'main:product' as product_url %}

<header class="sticky top-0 shadow z-50">
    <nav class="bg-white border-gray-200 px-4 lg:px-6 py-2.5 dark:bg-gray-800">
        <div class="relative flex flex-wrap justify-between items-center mx-auto max-w-screen-xl z-50">
            <a href="/" class="flex items-center">
                <img src="https://flowbite.com/docs/images/logo.svg" class="mr-3 h-6 sm:h-9" alt="Flowbite Logo"/>
                <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Defensive Eye</span>
            </a>
            <div class="flex items-center lg:order-2">
                {% if request.user.is_authenticated %}
                    {% include 'web/components/navbar_user_avatar.html' with show_info=True %}
                {% else %}
                    <a href="{% url 'accounts:login' %}"
                       class="hidden sm:inline-block btn btn-gradient-secondary btn-pill btn-sm md:btn-md    ">{% translate 'Log in' %}</a>
                    <a href="{% url 'accounts:register' %}"
                       class="btn btn-gradient-primary btn-pill btn-sm md:btn-md ">{% translate 'Get started' %}</a>
                {% endif %}
            </div>
            <div class="hidden justify-between items-center w-full lg:flex lg:w-auto lg:order-1" id="mobile-menu-2">
                <ul class="flex flex-col mt-4 font-medium lg:flex-row lg:space-x-8 lg:mt-0">
                    <li>
                        <a href="{{ home_url }}" class="link {% if active_tab == home_url %}active{% endif %}"
                           {% if active_tab == home_url %}aria-current="page"{% endif %}
                        >
                            {% translate 'Home' %}
                        </a>
                    </li>
                    <li>
                        <button id="mega-menu-trigger"
                                class="link {% if active_tab == product_url %}active{% endif %}">{% translate 'Products' %}</button>
                    </li>
                    <li>
                        <a href="#" class="link">{% translate 'About US' %}</a>
                    </li>
                    <li>
                        <a href="#" class="link">{% translate 'Contact US' %}</a>
                    </li>
                </ul>
            </div>
            {% include 'web/components/mega_menu.html' %}
        </div>
    </nav>
</header>

backend/templates/web/components/navbar_user_avatar.html
{% load i18n %}
<div id="avatarButton"
     class="relative w-10 h-10 overflow-hidden bg-gray-100 rounded-full dark:bg-gray-600 cursor-pointer"
     type="button" data-dropdown-toggle="userDropdown-{{ id }}" data-dropdown-placement="bottom-start">
    <svg class="absolute w-12 h-12 text-gray-400 -left-1" fill="currentColor" viewBox="0 0 20 20"
         xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path>
    </svg>
</div>


<!-- Dropdown menu -->
<div id="userDropdown-{{ id }}"
     class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
    {% if show_info == True %}
        <div class="px-4 py-3 text-sm text-gray-900 dark:text-white">
            <div>{{ request.user.get_full_name }}</div>
            <div class="font-medium truncate">{{ request.user.email }}</div>
        </div>
    {% endif %}
    <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="avatarButton">
        <li>
            <a href="{% url 'main:dashboard' %}"
               class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">
                {% translate 'Dashboard' %}
            </a>
        </li>
        <li>
            <a href="{% url 'shop:cart_detail' %}"
               class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">{% translate 'Shopping cart' %}</a>
        </li>
    </ul>
    <div class="py-1">
        <a href="{% url 'accounts:logout' %}"
           class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">
            {% translate 'Sign out' %}
        </a>
    </div>
</div>

backend/templates/web/components/sidebar.html
{% load i18n %}
{% url 'main:dashboard' as dashboard %}
{% url 'main:home' as home %}
{% url 'shop:order_history' as orders %}
{% url 'main:cameras_list' as cameras %}
{% url 'accounts:contact_list' as contacts %}
{% url 'accounts:subscription_list' as subscribes %}
{% url 'accounts:user_edit' as user_edit %}

<header class="sm:hidden sticky top-0 shadow z-30">
    <nav class="bg-white border-gray-200 px-4 lg:px-6 py-2.5 dark:bg-gray-800">
        <div class="relative flex flex-wrap justify-between items-center mx-auto max-w-screen-xl z-30">
            <button data-drawer-target="dashboard-sidebar" data-drawer-toggle="dashboard-sidebar"
                    aria-controls="dashboard-sidebar"
                    type="button"
                    class="inline-flex items-center p-2 mt-2 ml-3 text-sm text-gray-500 rounded-lg sm:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600">
                <span class="sr-only">Open sidebar</span>
                <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20"
                     xmlns="http://www.w3.org/2000/svg">
                    <path clip-rule="evenodd" fill-rule="evenodd"
                          d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"></path>
                </svg>
            </button>
            {% include 'web/components/navbar_user_avatar.html' with show_info=True id=0 %}
        </div>
    </nav>
</header>


<aside id="dashboard-sidebar"
       class="fixed lg:relative shrink-0 z-40 top-0 left-0 w-64 h-screen transition-transform shadow-lg -translate-x-full sm:translate-x-0"
       aria-label="Sidenav">
    <div class="overflow-y-auto py-5 px-3 h-full bg-white border-r border-gray-200 dark:bg-gray-800 dark:border-gray-700">
        <h2 class="text-xl font-bold text-primary-600">{% translate 'Eye Security Company' %}</h2>
        <ul class="space-y-2 mt-2 pt-2 border-t">
            <li>
                <a href="{{ dashboard }}"
                   class="sidebar-link group {% if active_tab == 'dashboard' %}active{% endif %}">
                    <span class="fa-light fa-grid-2 sidebar-icon"></span>
                    <span class="ml-3">{% translate 'Dashboard' %}</span>
                </a>
            </li>
            <li>
                <a href="{{ orders }}" class="sidebar-link group {% if active_tab == 'orders' %}active{% endif %}">
                    <span class="fa-light fa-cart-shopping sidebar-icon"></span>
                    <span class="ml-3">{% translate 'Orders' %}</span>
                </a>
            </li>
            <li>
                <a href="{{ cameras }}" class="sidebar-link group {% if active_tab == 'cameras' %}active{% endif %}">
                    <span class="fa-light fa-camera-cctv sidebar-icon"></span>
                    <span class="ml-3">{% translate 'Cameras' %}</span>
                </a>
            </li>
            <li>
                <a href="{{ contacts }}" class="sidebar-link group {% if active_tab == 'contacts' %}active{% endif %}">
                    <span class="fa-light fa-contact-book sidebar-icon"></span>
                    <span class="ml-3">{% translate 'Contacts' %}</span>
                </a>
            </li>
        </ul>
        <ul class="space-y-2 mt-2 pt-2 border-t">
            <li>
                <a href="{{ user_edit }}" class="sidebar-link group {% if active_tab == 'account' %}active{% endif %}">
                    <span class="fa-light fa-user sidebar-icon"></span>
                    <span class="ml-3">{% translate 'Account' %}</span>
                </a>
            </li>
            <li>
                <a href="{{ subscribes }}"
                   class="sidebar-link group {% if active_tab == 'subscriptions' %}active{% endif %}">
                    <span class="fa-light fa-sparkles sidebar-icon"></span>
                    <span class="ml-3">{% translate 'Subscription' %}</span>
                </a>
            </li>
            <li>
                <a href="{{ home }}"
                   class="sidebar-link group">
                    <span class="fa-light fa-door-open sidebar-icon"></span>
                    <span class="ml-3">{% translate 'Exit' %}</span>
                </a>
            </li>
        </ul>
    </div>
    <div class="hidden absolute bottom-0 left-0 justify-start p-4 space-x-4 w-full sm:flex bg-white dark:bg-gray-800 z-20 border-r border-gray-200 dark:border-gray-700">
        <div class="flex gap-2 items-center">
            {% include 'web/components/navbar_user_avatar.html' with show_info=False id=1 %}
            <div class="flex flex-col gap-1">
                <span class="">{{ request.user.get_full_name }}</span>
                <span class="">{{ request.user.email }}</span>
            </div>
        </div>
    </div>
</aside>

backend/templates/web/components/toast.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == "error" %}
            <div id="toast-danger-{{ forloop.counter }}"
                 class="toast toast-danger"
                 role="alert">
                <div class="toast-icon">
                    <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor"
                         viewBox="0 0 20 20">
                        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 11.793a1 1 0 1 1-1.414 1.414L10 11.414l-2.293 2.293a1 1 0 0 1-1.414-1.414L8.586 10 6.293 7.707a1 1 0 0 1 1.414-1.414L10 8.586l2.293-2.293a1 1 0 0 1 1.414 1.414L11.414 10l2.293 2.293Z"/>
                    </svg>
                    <span class="sr-only">Error icon</span>
                </div>
                <div class="ms-3 text-sm font-normal">{{ message }}</div>
                <button type="button"
                        class="ms-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex items-center justify-center h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700"
                        data-dismiss-target="#toast-danger-{{ forloop.counter }}" aria-label="Close">
                    <span class="sr-only">Close</span>
                    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                         viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                    </svg>
                </button>
            </div>
        {% elif message.tags == "success" %}
            <div id="toast-success"
                 class="toast toast-success"
                 role="alert">
                <div class="toast-icon">
                    <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor"
                         viewBox="0 0 20 20">
                        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z"/>
                    </svg>
                    <span class="sr-only">Check icon</span>
                </div>
                <div class="ms-3 text-sm font-normal">{{ message }}</div>
                <button type="button"
                        class="ms-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex items-center justify-center h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700"
                        data-dismiss-target="#toast-success" aria-label="Close">
                    <span class="sr-only">Close</span>
                    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                         viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                    </svg>
                </button>
            </div>
        {% elif message.tags == "warning" %}
            <div id="toast-warning"
                 class="toast toast-warning"
                 role="alert">
                <div class="toast-icon">
                    <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor"
                         viewBox="0 0 20 20">
                        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM10 15a1 1 0 1 1 0-2 1 1 0 0 1 0 2Zm1-4a1 1 0 0 1-2 0V6a1 1 0 0 1 2 0v5Z"/>
                    </svg>
                    <span class="sr-only">Warning icon</span>
                </div>
                <div class="ms-3 text-sm font-normal">{{ message }}</div>
                <button type="button"
                        class="ms-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex items-center justify-center h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700"
                        data-dismiss-target="#toast-warning" aria-label="Close">
                    <span class="sr-only">Close</span>
                    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                         viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                    </svg>
                </button>
            </div>
        {% else %}
            <div id="toast-default"
                 class="toast toast-info"
                 role="alert">
                <div class="toast-icon">
                    <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                         viewBox="0 0 18 20">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="M15.147 15.085a7.159 7.159 0 0 1-6.189 3.307A6.713 6.713 0 0 1 3.1 15.444c-2.679-4.513.287-8.737.888-9.548A4.373 4.373 0 0 0 5 1.608c1.287.953 6.445 3.218 5.537 10.5 1.5-1.122 2.706-3.01 2.853-6.14 1.433 1.049 3.993 5.395 1.757 9.117Z"/>
                    </svg>
                    <span class="sr-only">Fire icon</span>
                </div>
                <div class="ms-3 text-sm font-normal">{{ message }}</div>
                <button type="button"
                        class="ms-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex items-center justify-center h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700"
                        data-dismiss-target="#toast-default" aria-label="Close">
                    <span class="sr-only">Close</span>
                    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                         viewBox="0 0 14 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                    </svg>
                </button>
            </div>
        {% endif %}
    {% endfor %}
{% endif %}